name: "elites-team/git-subtree"
description: "Sync a sub-directory from a parent repo to a child repository (git subtree.)"
inputs:
  action:
    description: "subtree action (pull or push)"
    required: true
  path:
    description: "Path prefix in parent repo to split into child subtree (eg. src/PackageName.)"
    required: true
  repo:
    description: "Child repository to sync the subtree to (eg. owner/repository.)"
    required: true
  branch:
    description: "Branch of child subtree repository (default is branch or tag ref that triggered the workflow.)"
    required: false
    default: ""
  message:
    description: "merge message"
    required: false
    default: ""
  deploy_key:
    ## Use a repo/org secret for this value. ##
    description: "Deployment SSH key for pushing to child repo (checkout out deployment tokens for single repos or bot accounts for multi-repos/orgs.)"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: share-2
  color: blue
